
create_ip -name hbm -vendor xilinx.com -library ip -module_name hbm_0

set_property -dict [list \
    CONFIG.USER_HBM_DENSITY {8GB} \
    CONFIG.USER_HBM_STACK {2} \
    CONFIG.USER_MC0_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC1_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC2_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC3_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC4_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC5_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC6_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC7_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC8_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC9_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC10_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC11_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC12_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC13_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC14_ENABLE_ECC_CORRECTION {true} \
    CONFIG.USER_MC15_ENABLE_ECC_CORRECTION {true}
] [get_ips hbm_0]
